-- Wanderloom — ROLLBACK for 2026-10-07_phase1_lockdown.sql
-- Restores policies, RLS flags and anon table grants exactly as captured on 2026-10-07 before the lockdown.
begin;
do $$ declare t record; p record; begin
  for t in select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' loop
    for p in select policyname from pg_policies where schemaname='public' and tablename=t.relname loop
      execute format('drop policy %I on public.%I', p.policyname, t.relname);
    end loop;
    execute format('revoke all on table public.%I from anon', t.relname);
  end loop; end $$;
alter table public."countries" enable row level security;
alter table public."client_preferences" enable row level security;
alter table public."celebrities" enable row level security;
alter table public."client_notes" enable row level security;
alter table public."client_trips" enable row level security;
alter table public."itinerary_stops" enable row level security;
alter table public."edit_requests" enable row level security;
alter table public."wow_tasks" enable row level security;
alter table public."group_tours" enable row level security;
alter table public."group_travelers" enable row level security;
alter table public."places" enable row level security;
alter table public."itinerary_days" enable row level security;
alter table public."events" enable row level security;
alter table public."travel_wardrobe" disable row level security;
alter table public."trip_budget" enable row level security;
alter table public."hotels" disable row level security;
alter table public."tour_groups" disable row level security;
alter table public."itinerary_templates" enable row level security;
alter table public."destinations_guide" disable row level security;
alter table public."secret_places" enable row level security;
alter table public."suppliers" enable row level security;
alter table public."marketing_human_scripts" disable row level security;
alter table public."marketing_ai_prompts" disable row level security;
alter table public."marketing_calendar" disable row level security;
alter table public."brand_identity" disable row level security;
alter table public."memory_vault" disable row level security;
alter table public."sessions" disable row level security;
alter table public."experiences" disable row level security;
alter table public."client_memories" disable row level security;
alter table public."leads" disable row level security;
alter table public."wallet_transactions" enable row level security;
alter table public."influencers" disable row level security;
alter table public."employees" disable row level security;
alter table public."session_registrations" disable row level security;
alter table public."invoices" enable row level security;
alter table public."client_reviews" enable row level security;
alter table public."leader_availability" enable row level security;
alter table public."trip_logs" enable row level security;
alter table public."expert_suppliers" enable row level security;
alter table public."itineraries" enable row level security;
alter table public."group_pricings" enable row level security;
alter table public."crm_record_comments" enable row level security;
alter table public."proposal_templates" enable row level security;
alter table public."system_settings" enable row level security;
alter table public."marketing_content" enable row level security;
alter table public."group_trips" enable row level security;
alter table public."clients" enable row level security;
alter table public."group_members" enable row level security;
alter table public."quotations" enable row level security;
alter table public."leaders" enable row level security;
alter table public."activity_logs" enable row level security;
alter table public."ai_consultations" enable row level security;
alter table public."experts" enable row level security;
create policy "staff_all" on public."clients" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."client_preferences" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."client_notes" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."client_trips" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."places" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."events" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."itineraries" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."itinerary_days" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."itinerary_stops" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "staff_all" on public."edit_requests" as permissive for all to public using ((auth.role() = 'authenticated'::text));
create policy "portal_read" on public."itineraries" as permissive for select to public using (true);
create policy "portal_read" on public."itinerary_days" as permissive for select to public using (true);
create policy "portal_read" on public."itinerary_stops" as permissive for select to public using (true);
create policy "portal_read" on public."places" as permissive for select to public using (true);
create policy "portal_insert" on public."edit_requests" as permissive for insert to public with check (true);
create policy "public_read_clients" on public."clients" as permissive for select to public using (true);
create policy "public_read_places" on public."places" as permissive for select to public using (true);
create policy "public_read_events" on public."events" as permissive for select to public using (true);
create policy "public_read_trips" on public."client_trips" as permissive for select to public using (true);
create policy "public_write_trips" on public."client_trips" as permissive for insert to public with check (true);
create policy "public_read_notes" on public."client_notes" as permissive for select to public using (true);
create policy "public_write_notes" on public."client_notes" as permissive for insert to public with check (true);
create policy "public_read_prefs" on public."client_preferences" as permissive for select to public using (true);
create policy "public_write_prefs" on public."client_preferences" as permissive for update to public using (true);
create policy "public_update_clients" on public."clients" as permissive for update to public using (true);
create policy "public_update_trips" on public."client_trips" as permissive for update to public using (true);
create policy "public_delete_trips" on public."client_trips" as permissive for delete to public using (true);
create policy "public_write_itineraries" on public."itineraries" as permissive for insert to public with check (true);
create policy "public_update_itineraries" on public."itineraries" as permissive for update to public using (true);
create policy "public_write_days" on public."itinerary_days" as permissive for insert to public with check (true);
create policy "public_write_stops" on public."itinerary_stops" as permissive for insert to public with check (true);
create policy "public_update_places" on public."places" as permissive for update to public using (true);
create policy "public_update_events" on public."events" as permissive for update to public using (true);
create policy "public_write_events" on public."events" as permissive for insert to public with check (true);
create policy "public_delete_itineraries" on public."itineraries" as permissive for delete to public using (true);
create policy "public_delete_days" on public."itinerary_days" as permissive for delete to public using (true);
create policy "public_delete_stops" on public."itinerary_stops" as permissive for delete to public using (true);
create policy "public_update_days" on public."itinerary_days" as permissive for update to public using (true);
create policy "public_update_stops" on public."itinerary_stops" as permissive for update to public using (true);
create policy "public_insert_places" on public."places" as permissive for insert to public with check (true);
create policy "public_delete_places" on public."places" as permissive for delete to public using (true);
create policy "public_delete_trips2" on public."client_trips" as permissive for delete to public using (true);
create policy "public_update_trips2" on public."client_trips" as permissive for update to public using (true);
create policy "public_all_budget" on public."trip_budget" as permissive for all to public using (true);
create policy "Public Access" on public."memory_vault" as permissive for all to public using (true);
create policy "Allow All" on public."tour_groups" as permissive for all to public using (true);
create policy "Allow All" on public."group_members" as permissive for all to public using (true);
create policy "Enable read access for all users" on public."suppliers" as permissive for select to public using (true);
create policy "Enable full access for CRM users" on public."clients" as permissive for all to public using (true);
create policy "Enable public read access for itineraries" on public."itineraries" as permissive for select to public using (true);
create policy "السماح للجميع بقراءة الرحلات" on public."group_trips" as permissive for select to public using (true);
create policy "السماح بالإضافة" on public."group_trips" as permissive for insert to public with check (true);
create policy "السماح بالتعديل" on public."group_trips" as permissive for update to public using (true);
create policy "السماح بالحذف" on public."group_trips" as permissive for delete to public using (true);
create policy "Allow All" on public."influencers" as permissive for all to public using (true);
create policy "Allow all on templates" on public."itinerary_templates" as permissive for all to public using (true) with check (true);
create policy "Enable full access for authenticated users" on public."quotations" as permissive for all to authenticated using (true) with check (true);
create policy "Allow read access for experts" on public."experts" as permissive for select to public using (true);
create policy "Allow read access for leaders" on public."leaders" as permissive for select to public using (true);
create policy "Allow read access for wallet_transactions" on public."wallet_transactions" as permissive for select to public using (true);
create policy "Allow authenticated users to read comments" on public."crm_record_comments" as permissive for select to authenticated using (true);
create policy "Allow authenticated users to insert comments" on public."crm_record_comments" as permissive for insert to authenticated with check (true);
create policy "Allow full access for group_pricings" on public."group_pricings" as permissive for all to public using (true) with check (true);
create policy "Allow read itineraries" on public."itineraries" as permissive for select to public using (true);
create policy "Allow read clients" on public."clients" as permissive for select to public using (true);
create policy "Allow read leaders" on public."leaders" as permissive for select to public using (true);
create policy "Allow public read access to leaders" on public."leaders" as permissive for select to public using (true);
create policy "Enable read access for all users" on public."leaders" as permissive for select to public using (true);
create policy "Allow public select on leaders" on public."leaders" as permissive for select to public using (true);
create policy "Allow public select on itineraries" on public."itineraries" as permissive for select to public using (true);
create policy "Allow public insert to clients" on public."clients" as permissive for insert to public with check (true);
create policy "Allow public select on clients" on public."clients" as permissive for select to public using (true);
create policy "Enable update for all users" on public."group_members" as permissive for update to public using (true);
create policy "Enable delete for all users" on public."group_members" as permissive for delete to public using (true);
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."activity_logs" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."ai_consultations" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."brand_identity" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."celebrities" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."client_memories" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."client_notes" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."client_preferences" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."client_reviews" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."client_trips" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."clients" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."countries" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."crm_record_comments" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."destinations_guide" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."distinct_cities" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."distinct_countries" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."edit_requests" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."employees" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."events" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."experiences" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."expert_suppliers" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."experts" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."global_destinations" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."group_members" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."group_pricings" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."group_tours" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."group_travelers" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."group_trips" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."hotels" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."influencers" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."invoices" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."itineraries" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."itinerary_days" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."itinerary_stops" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."itinerary_templates" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."leader_availability" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."leaders" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."leads" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."marketing_ai_prompts" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."marketing_calendar" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."marketing_content" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."marketing_human_scripts" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."memory_vault" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."places" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."proposal_templates" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."quotations" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."secret_places" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."session_registrations" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."sessions" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."suppliers" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."system_settings" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."tour_groups" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."travel_wardrobe" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."trip_budget" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."trip_logs" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."wallet_transactions" to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public."wow_tasks" to anon;
alter view public.distinct_countries reset (security_invoker);
alter view public.distinct_cities reset (security_invoker);
alter view public.global_destinations reset (security_invoker);
grant execute on function public.get_or_create_client_id(text, text) to public, anon, authenticated;
drop function if exists public.is_staff();
drop function if exists public.is_admin_staff();
commit;
