-- عروض الأسعار — منفصلة عن جدول itineraries (المسارات المؤكدة)
create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients (id) on delete set null,
  title text not null default '',
  destinations text[] not null default '{}',
  start_date date,
  end_date date,
  total_estimated_cost numeric(12, 2) not null default 0,
  expected_profit numeric(12, 2) not null default 0,
  status text not null default 'pending_client'
    check (status in ('draft', 'pending_client', 'approved')),
  flight_proposals jsonb not null default '[]'::jsonb,
  hotel_proposals jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.quotations is 'عروض أسعار المبيعات — قبل تحويلها لمسار مؤكد';
comment on column public.quotations.destinations is 'وجهات الرحلة (مصفوفة نصية)';
comment on column public.quotations.flight_proposals is '[{ departureCity, arrivalCity, airline, flight_class }]';
comment on column public.quotations.hotel_proposals is '[{ hotel_name, city, room_type }]';

create index if not exists quotations_client_id_idx on public.quotations (client_id);
create index if not exists quotations_status_idx on public.quotations (status);
create index if not exists quotations_created_at_idx on public.quotations (created_at desc);

alter table public.quotations enable row level security;

drop policy if exists "quotations_crm_select" on public.quotations;
create policy "quotations_crm_select"
  on public.quotations for select
  to anon, authenticated
  using (true);

drop policy if exists "quotations_crm_insert" on public.quotations;
create policy "quotations_crm_insert"
  on public.quotations for insert
  to anon, authenticated
  with check (true);

drop policy if exists "quotations_crm_update" on public.quotations;
create policy "quotations_crm_update"
  on public.quotations for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "quotations_crm_delete" on public.quotations;
create policy "quotations_crm_delete"
  on public.quotations for delete
  to anon, authenticated
  using (true);
